# Project Information
sonar.projectKey=student-api
sonar.projectName=Student API
sonar.projectVersion=1.0

# Source Code
sonar.sources=app
sonar.tests=tests

# Python Version
sonar.python.version=3.9

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage Report
sonar.python.coverage.reportPaths=coverage.xml